server:
  port: "8080"
  read_timeout: 10
  write_timeout: 10

database:
  host: ${DATABASE_HOST:-postgres}
  port: ${DATABASE_PORT:-5432}
  user: ${DATABASE_USER:-insdr}
  password: ${DATABASE_PASSWORD:-password}
  dbname: ${DATABASE_DBNAME:-insdr_db}
  sslmode: ${DATABASE_SSLMODE:-require}

redis:
  host: ${REDIS_HOST:-redis}
  port: ${REDIS_PORT:-6379}
  password: ${REDIS_PASSWORD:-}
  db: ${REDIS_DB:-0}

webhook:
  url: ${WEBHOOK_URL}
  auth_key: ${WEBHOOK_AUTH_KEY}
  timeout: ${WEBHOOK_TIMEOUT:-30}

scheduler:
  interval_minutes: ${SCHEDULER_INTERVAL:-2}
  batch_size: ${SCHEDULER_BATCH_SIZE:-2}

middleware:
  enable_auth: true
  api_key: ${API_KEY}
  rate_limit: ${RATE_LIMIT:-50}
  rate_limit_burst: ${RATE_LIMIT_BURST:-200}
  enable_cors: true