services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: insider
      POSTGRES_PASSWORD: password
      POSTGRES_DB: insider_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U insider"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: insider
      DATABASE_PASSWORD: password
      DATABASE_DBNAME: insider_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./config.docker.yaml:/app/config.yaml:ro
      - ./migrations:/app/migrations:ro
    restart: unless-stopped
    command: ["/app/insider-messenger"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
  redis_data: